remote_theme: just-the-docs/just-the-docs
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/aimedlogo.webp"

aux_links:
  "AI.MED LAB Website":
    - "https://aimed-lab.org/"


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 <a href=\"https://aimed-lab.org/\">AI.MED LAB</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html